# Generated by Django 4.1.3 on 2022-12-20 17:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('servicio', models.CharField(choices=[(1, 'Netflix'), (2, 'Amazon Video'), (3, 'Star +'), (4, 'Paramount +')], max_length=1)),
                ('fecha_pago', models.DateTimeField(auto_now_add=True)),
                ('monto', models.FloatField(default=0.0)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
